{
  "Header": {
    "Original": "CVE-2020-24372 (LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in  ...)",
    "ID": "CVE-2020-24372",
    "Description": "(LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-4283-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-4283-1"
      ]
    },
    {
      "Original": "- luajit 2.1.0~beta3+git20210112+dfsg-2 (unimportant)",
      "Type": "package",
      "Package": "luajit",
      "Kind": "fixed",
      "Version": "2.1.0~beta3+git20210112+dfsg-2",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/LuaJIT/LuaJIT/issues/603",
      "Type": "NOTE",
      "Description": "https://github.com/LuaJIT/LuaJIT/issues/603"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/LuaJIT/LuaJIT/commit/12ab596997b9cb27846a5b254d11230c3f9c50c8 (v2.1)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/LuaJIT/LuaJIT/commit/12ab596997b9cb27846a5b254d11230c3f9c50c8 (v2.1)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/LuaJIT/LuaJIT/commit/e296f56b825c688c3530a981dc6b495d972f3d01 (v2.1)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/LuaJIT/LuaJIT/commit/e296f56b825c688c3530a981dc6b495d972f3d01 (v2.1)"
    },
    {
      "Original": "NOTE: No security impact, only \"exploitable\" with untrusted Lua code",
      "Type": "NOTE",
      "Description": "No security impact, only \"exploitable\" with untrusted Lua code"
    }
  ]
}